# Generated by Django 4.0.2 on 2022-02-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mixins.listitem', verbose_name='Elemento padre'),
        ),
        migrations.AlterField(
            model_name='listtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mixins.listtype', verbose_name='Tipo de lista padre'),
        ),
    ]
