# Generated by Django 4.0.2 on 2022-02-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_file_product_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='file',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='file',
            name='published',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_by',
        ),
    ]
